# Generated by Django 2.2.3 on 2019-09-16 00:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myfurniturereviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Furnitures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Euro amount')),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myrestaurants')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='user',
        ),
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='FurnitureShop',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='RestaurantReview',
        ),
        migrations.AddField(
            model_name='furnitures',
            name='furnitureshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='furni', to='myfurniturereviews.FurnitureShop'),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='furniturereview',
            name='furnitureshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfurniturereviews.FurnitureShop'),
        ),
        migrations.AddField(
            model_name='furniturereview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
